### ISSUE TITLE
Scanning Process-camera suddenly stopped

### ISSUE THREAD

**Issue by sbasnagala** [evo-biomech/scAnt#6] opened 2022-03-31 14:38 UTC
HI,
Here are the steps I followed so far before the camera stopped at the middle of the slider.
1. Checked the Exposure auto and gain auto boxes.
2. started 'Start live scan'
3. Home X-axis
4. Home focus – then adjusted the focus level.
5. Brought the x-axis to furthest away from the camera and focused the closest position of the specimen and it is -42881.
6. focused on the furthest position by driving the camera forward and it is -16525.  
7. Unchecked the Exposure auto and Gain auto and define the output folder. Check the 'stack images' box.
8. start scan

After taking 15 images camera stopped at -33381. 
I have 20GB of free space on my computer. Hope it is not a space issue.
The screenshot is attached where the camera stopped
![image 6](https://user-images.githubusercontent.com/102258948/161081615-d90e4e81-e2df-4653-ae7c-da772cd811c7.jpg)
.

**Comment by sbasnagala** [comment] 2022-03-31 18:00
Thanks!! everything seems working fine. I tried a few times, but the scanner progress bar goes for 3% and it's doing nothing after that. 69  Images were taken and stored during that time.
![image 7](https://user-images.githubusercontent.com/102258948/161120288-2299dc5c-fcca-4e46-a02f-005f2c1ff6a1.jpg)
.

**Comment by sbasnagala** [comment] 2022-03-31 18:41
I am running on WIN 10 on DELL with 8GB RAM, i5, intel 4 core. 3 TB Hard drive to save images.

**Comment by FabianPlum** [comment] 2022-03-31 20:43
Could you post a screenshot of the task manager and resource utilisation while running a scan?

**Comment by sbasnagala** [comment] 2022-04-01 12:33
Here they are.
![task manager](https://user-images.githubusercontent.com/102258948/161264185-e1d14509-4caa-47f4-8106-5c68b27611d9.jpg)
![Resource Uti](https://user-images.githubusercontent.com/102258948/161264194-0db135b0-8dda-41ee-93bc-2763a788009c.jpg)

**Comment by sbasnagala** [comment] 2022-04-01 13:25
camera is still stops at between 1-2%. Here is the settings just before scan with furthest point of the specimen is in focus (Insect antennae). Is 'Home X axis' and 'Min [X Axis] values in right place, or it has to be vice versa?
Everything looks ok to me here, but couldn't figure out why the camera stops after taking 40 - 50 images. I took most of my background applications off including screen savers.
![image 8](https://user-images.githubusercontent.com/102258948/161272290-6d69bde8-b989-42c5-8f25-bd4ac53732d5.jpg)

**Comment by FabianPlum** [comment] 2022-04-01 13:35
The settings seem mostly fine to me. 
However, your output folder path has spaces, which is not recommended for file paths. Consider replacing spaces with underscores, or hyphens. In the case above, I recommend using **D:/SCANT_IMAGES/StinkBug/sb_9**, so you should change the respective folder names.

Did you, by any chance, click into the console while running the scan? If so, click into it again and press enter, then click out of it to have the program resume. 

I have not seen this kind of "stuck" behaviour from the code before, outside of lack of computational resources. Do you by any chance have another computer to test the program?

**Comment by sbasnagala** [comment] 2022-04-01 19:43
I tried all except using another computer. Each and every time the scanning process halt before reaching 3%. When I opened POLOLU tic control center app - it says "motor holding because of the command timeout" for all 3 steppers. I pressed ''Resume" in tic controllers, but it did not drive the motors. "RESUME" button in the GUI is disabled and can not be de-energized. Any idea what the issue is?

**Comment by sbasnagala** [comment] 2022-04-01 20:16
Also, I increased the step size on X, Y and Z  to 100, 80 and 3000 by allowing to take fewer images, and the scan lasted 15% before stop.

**Comment by sbasnagala** [comment] 2022-04-01 20:18
Just noticed, when I enter Min [Z Axis] value, the command prompt indicate it as "INPUT ERROR FOUND!"

**Comment by FabianPlum** [comment] 2022-04-01 20:22
The adjustments for X and Y are reasonable but a 3000 step-size might be too coarse. The reason you get an input error when entering the min value is, that it is initially **higher** than the max value before you finish entering it. 

Trying to restart the motors from the tic control program is not advisable, as it will overwrite motor commands from scAnt and prevent it from running correctly.

**Comment by FabianPlum** [comment] 2022-04-01 20:26
Could you try to use the software on a different computer? I strongly suspect that your system cannot handle the requirements of the program. As I cannot reproduce the issue you are having on my machine it is very difficult to find a solution remotely.

**Comment by sbasnagala** [comment] 2022-04-01 20:27
I just tried increasing the step size further. X and Y axis worked perfectly for 62% until stop the motors. I can try with another computer and will let you know the progress. I am getting there I think...Thanks!!

**Comment by FabianPlum** [comment] 2022-04-05 10:31
Hi @sbasnagala
Did you end up resolving the problems you had? If so, would you mind sharing those steps here, so we can document / implement the fix?

**Comment by sbasnagala** [comment] 2022-04-05 10:44
Hi Fabian,
I am working with out IT department now. I can not upgrade the computer by myself. Unfortunately it will take time. I will post my comments as soon as I have them.

**Comment by sbasnagala** [comment] 2022-04-06 18:09
*### *SCANNER RAN SUCCESSFULLY!!!!!!**

I checked my workstation with a IT guy while running the scanner. We saw something is happening to the CPU graph just before it stopped. Basically it is like CPU trying to max out and unable to hold the load. SO I brought my personnel computer to workplace (Specs- Win 10, core i7-8700, 3.2GHz, 6 Core with 24GB RAM).
After installing Anaconda and other related software, code instructions etc., I ran the scanner successfully. That was my first full scan I did for the first time. 3500 + images.. WOW!!! I know now my other work workstation is not capable of handling the scanner, so time to upgrade.
All the images were written to a external hard drive successfully. I also noticed that the specimen is not centered properly. It is circling when rotating the Y axis. I need to work on how to perfectly straighten up the specimen.

Thanks Fabian!!!. Now I need to figure out the next step, "Construction of the 3D model"

**Comment by FabianPlum** [comment] 2022-04-07 09:11
Hi @sbasnagala,
 
So glad to hear your scAnt is finally up and scanning!
I'll add details on minimum system requirements in the **readme** to let others know what hardware they need to run everything smoothly.

All the best
Fabi

**Closed by FabianPlum** 2022-04-07 09:11 UTC
Labels: help wanted

**Comment by sbasnagala** [comment] 2022-04-11 13:18
Hi Fabian,
Yes please do. My old workstation is 
Processor	Intel(R) Core(TM) i5-8350U CPU @ 1.70GHz, 1896 MHz, 4 Core(s), 8 Logical Processor(s)
Installed Physical Memory (RAM)	8.00 GB

HDD and memory seems to be fine when I ran the scanner. We saw a spike in the CPU just before it stopped. So I ran the scanner with my personnel machine which is a HP i7-8700 with 16GB memory without any issues. 

Suranga
