### ISSUE TITLE
Issue with GUI file

### ISSUE THREAD

**Issue by CharliePoore01** [evo-biomech/scAnt#8] opened 2022-04-20 11:36 UTC
Followed all steps including downloading and setting up conda envrinment, connecting and testing camera and setting up stepper motors. We know the DSLR camera is working with it (tested using Live_view_DSLR.py) and the stepper motors are working as well using tic controller software. The scAnt_GUI_mw.py file in the GUI folder launches the GUI, but the camera is not listed and the "browse" buttons under Output folder and Load presets do not work in addition to the stepper motors being inactive ... any ideas?

Thanks 
Charlie

**Comment by FabianPlum** [comment] 2022-04-20 11:40
Hi Charlie,
The **scAnt_GUI_mw.py** file only contains the generated window but with no functionality.

You need to run `python scAnt.py` for the actual scanner software.

Lemme know how that goes!

All the best Fabi

**Comment by CharliePoore01** [comment] 2022-04-20 12:41
Hi Fabi, 
when trying to run the python scAnt.py i get this error message:

ModuleNotFoundError
Python 3.7.12: C:\Users\charl\anaconda3\envs\scant\python.exe
Wed Apr 20 13:39:51 2022

A problem occurred in a Python script.  Here is the sequence of
function calls leading up to the error, in the order they occurred.

 C:\Users\charl\OneDrive\Desktop\scAnt-master\scAnt.py in <module>()
 1286     app = QtWidgets.QApplication([])
 1287
 1288     application = scAnt_mainWindow()
 1289
 1290     application.show()
application undefined
scAnt_mainWindow = <class '__main__.scAnt_mainWindow'>

 C:\Users\charl\OneDrive\Desktop\scAnt-master\scAnt.py in __init__(self=<__main__.scAnt_mainWindow object>)
  135         # Find FLIR cameras, if attached
  136         try:
  137             from GUI.Live_view_FLIR import customFLIR
  138             self.FLIR = customFLIR()
  139             # camera needs to be initialised before use (self.cam.initialise_camera)
GUI undefined
customFLIR undefined

 C:\Users\charl\OneDrive\Desktop\scAnt-master\GUI\Live_view_FLIR.py in <module>()
   10     import PySpin
   11 else:
   12     from PySpin import PySpin  # to run on windows
   13
   14
PySpin undefined
ModuleNotFoundError: No module named 'PySpin'
    __cause__ = None
    __class__ = <class 'ModuleNotFoundError'>
    __context__ = None
    __delattr__ = <method-wrapper '__delattr__' of ModuleNotFoundError object>
    __dict__ = {}
    __dir__ = <built-in method __dir__ of ModuleNotFoundError object>
    __doc__ = 'Module not found.'
    __eq__ = <method-wrapper '__eq__' of ModuleNotFoundError object>
    __format__ = <built-in method __format__ of ModuleNotFoundError object>
    __ge__ = <method-wrapper '__ge__' of ModuleNotFoundError object>
    __getattribute__ = <method-wrapper '__getattribute__' of ModuleNotFoundError object>
    __gt__ = <method-wrapper '__gt__' of ModuleNotFoundError object>
    __hash__ = <method-wrapper '__hash__' of ModuleNotFoundError object>
    __init__ = <method-wrapper '__init__' of ModuleNotFoundError object>
    __init_subclass__ = <built-in method __init_subclass__ of type object>
    __le__ = <method-wrapper '__le__' of ModuleNotFoundError object>
    __lt__ = <method-wrapper '__lt__' of ModuleNotFoundError object>
    __ne__ = <method-wrapper '__ne__' of ModuleNotFoundError object>
    __new__ = <built-in method __new__ of type object>
    __reduce__ = <built-in method __reduce__ of ModuleNotFoundError object>
    __reduce_ex__ = <built-in method __reduce_ex__ of ModuleNotFoundError object>
    __repr__ = <method-wrapper '__repr__' of ModuleNotFoundError object>
    __setattr__ = <method-wrapper '__setattr__' of ModuleNotFoundError object>
    __setstate__ = <built-in method __setstate__ of ModuleNotFoundError object>
    __sizeof__ = <built-in method __sizeof__ of ModuleNotFoundError object>
    __str__ = <method-wrapper '__str__' of ModuleNotFoundError object>
    __subclasshook__ = <built-in method __subclasshook__ of type object>
    __suppress_context__ = False
    __traceback__ = <traceback object>
    args = ("No module named 'PySpin'",)
    msg = "No module named 'PySpin'"
    name = 'PySpin'
    path = None
    with_traceback = <built-in method with_traceback of ModuleNotFoundError object>

The above is a description of an error in a Python program.  Here is
the original traceback:

Traceback (most recent call last):
  File "scAnt.py", line 1288, in <module>
    application = scAnt_mainWindow()
  File "scAnt.py", line 137, in __init__
    from GUI.Live_view_FLIR import customFLIR
  File "C:\Users\charl\OneDrive\Desktop\scAnt-master\GUI\Live_view_FLIR.py", line 12, in <module>
    from PySpin import PySpin  # to run on windows
ModuleNotFoundError: No module named 'PySpin'

**Comment by CharliePoore01** [comment] 2022-04-20 14:57
I have noticed your reply to a previous comment to what I believe to be a similar problem mentioned making sure that DigiCamControl is installed to 'C:Program Files (x86)/digiCamControl' this is where I have it installed so I am assuming I don't need to change anything in the LiveViewDSLR.py file or am I incorrect? 
Thanks 
Charlie

**Comment by FabianPlum** [comment] 2022-04-21 09:53
If your path is the same, you should not have to update it in **LiveViewDSLR.py**. However, to be sure, you could copy the full path into:

```
# Update with the path to CameraControlCmd.exe file.
digi_cam_path = Path("C:\Program Files (x86)\digiCamControl")  #or wherever the location of your installation is
```
There used to be an issue where PySpin needed to be installed regardless of whether FLIR cams were used, but that should have been resolved in 00e452805f3be1da2226a5fa73f32a6dea090d7a 

Could you try pulling/downloading the latest version of the scAnt repo and try running `python scAnt.py` again?

**Comment by FabianPlum** [comment] 2022-04-26 17:18
Hey @CharliePoore01,

Could you check if the fix is working for you now?
If so, I'll close this thread.

All the best Fabi

**Comment by CharliePoore01** [comment] 2022-04-26 17:27
Hi @FabianPlum I won’t have access to the scanner until the end of this week/start of next week. If you would like to close it I’ll email you privately when I have been able to test.

**Comment by FabianPlum** [comment] 2022-04-26 17:29
Nah, there is no urgency!
Just wanted to make sure the issue is solved for you

**Comment by FabianPlum** [comment] 2022-05-27 09:31
Okay, I'll close the issue for now, as there is no more activity here. If the issue persists on your end, you can always reopen the issue or submit a new one!

All the best
Fabi

**Closed by FabianPlum** 2022-05-27 09:31 UTC
Labels: bug
